// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

type ErrCode int32

const (
	ErrCode_ErrOk       ErrCode = 0
	ErrCode_PARAM_ERROR ErrCode = 100003
)

var (
	ErrCode_name = map[int32]string{
		0:      "ErrOk",
		100003: "PARAM_ERROR",
	}
	ErrCode_value = map[string]int32{
		"ErrOk":       0,
		"PARAM_ERROR": 100003,
	}
)

func OneOfErrCode(i int32) bool {
	_, ok := ErrCode_name[i]
	return ok
}
