// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
)

type GS_PROJECT_NAMEServer interface {
	CreateOrder(context.Context, *CreateOrderReq) *CreateOrderResp
	PayOrder(context.Context, *PayOrderReq) *PayOrderResp
	Ping(context.Context, *PingReq) *PingResp
	RegisterUser(context.Context, *RegisterUserReq) *RegisterUserResp
	ShipOrder(context.Context, *ShipOrderReq) *ShipOrderResp
	UpgradeUser(context.Context, *UpgradeUserReq) *UpgradeUserResp
}

func InitRouter(mux *http.ServeMux, server GS_PROJECT_NAMEServer) {
	mux.HandleFunc("POST /createOrder", JSON(server.CreateOrder))
	mux.HandleFunc("POST /payOrder", JSON(server.PayOrder))
	mux.HandleFunc("GET /ping", JSON(server.Ping))
	mux.HandleFunc("POST /registerUser", JSON(server.RegisterUser))
	mux.HandleFunc("POST /shipOrder", JSON(server.ShipOrder))
	mux.HandleFunc("POST /upgradeUser", JSON(server.UpgradeUser))
}

func ReadRequest(r *http.Request, i interface{}) error {
	b, err := io.ReadAll(r.Body)
	if err != nil {
		return err
	}
	if len(b) == 0 {
		return nil
	}
	return json.Unmarshal(b, i)
}

func WriteResponse(w http.ResponseWriter, i interface{}) {
	b, err := json.Marshal(i)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if _, err = w.Write(b); err != nil {
		return
	}
}

func JSON[Req interface{ New() any }, Resp any](h func(context.Context, Req) Resp) http.HandlerFunc {
	var x Req
	return func(w http.ResponseWriter, r *http.Request) {
		req := x.New().(Req)
		if err := ReadRequest(r, req); err != nil {
			WriteResponse(w, err)
			return
		}
		res := h(r.Context(), req)
		WriteResponse(w, res)
	}
}
