// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"fmt"
)

type OrderStatus int32

const (
	OrderStatus_Pending OrderStatus = 0
	OrderStatus_Paid    OrderStatus = 1
	OrderStatus_Shipped OrderStatus = 2
)

var (
	OrderStatus_name = map[int32]string{
		0: "Pending",
		1: "Paid",
		2: "Shipped",
	}
	OrderStatus_value = map[string]int32{
		"Pending": 0,
		"Paid":    1,
		"Shipped": 2,
	}
)

func OneOfOrderStatus(i int32) bool {
	_, ok := OrderStatus_name[i]
	return ok
}

type Order struct {
	Id     string      `json:"id"`
	UserId string      `json:"user_id"`
	Amount float64     `json:"amount"`
	Status OrderStatus `json:"status"`
}

func NewOrder() *Order {
	return &Order{}
}

func (x *Order) New() any {
	return NewOrder()
}

func (x *Order) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *Order) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *Order) GetUserId() (r string) {
	if x != nil {
		return x.UserId
	}
	return r
}

func (x *Order) SetUserId(v string) {
	if x != nil {
		x.UserId = v
	}
}

func (x *Order) GetAmount() (r float64) {
	if x != nil {
		return x.Amount
	}
	return r
}

func (x *Order) SetAmount(v float64) {
	if x != nil {
		x.Amount = v
	}
}

func (x *Order) GetStatus() (r OrderStatus) {
	if x != nil {
		return x.Status
	}
	return r
}

func (x *Order) SetStatus(v OrderStatus) {
	if x != nil {
		x.Status = v
	}
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

type CreateOrderReq struct {
	Id     string  `json:"id"`
	UserId string  `json:"user_id"`
	Amount float64 `json:"amount"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (x *CreateOrderReq) New() any {
	return NewCreateOrderReq()
}

func (x *CreateOrderReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *CreateOrderReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *CreateOrderReq) GetUserId() (r string) {
	if x != nil {
		return x.UserId
	}
	return r
}

func (x *CreateOrderReq) SetUserId(v string) {
	if x != nil {
		x.UserId = v
	}
}

func (x *CreateOrderReq) GetAmount() (r float64) {
	if x != nil {
		return x.Amount
	}
	return r
}

func (x *CreateOrderReq) SetAmount(v float64) {
	if x != nil {
		x.Amount = v
	}
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

type CreateOrderResp struct {
	Errno  ErrCode `json:"errno"`
	Errmsg string  `json:"errmsg"`
	Data   *Order  `json:"data"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

func (x *CreateOrderResp) New() any {
	return NewCreateOrderResp()
}

func (x *CreateOrderResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *CreateOrderResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

func (x *CreateOrderResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *CreateOrderResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *CreateOrderResp) GetData() (r *Order) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *CreateOrderResp) SetData(v *Order) {
	if x != nil {
		x.Data = v
	}
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

type PayOrderReq struct {
	Id string `json:"id"`
}

func NewPayOrderReq() *PayOrderReq {
	return &PayOrderReq{}
}

func (x *PayOrderReq) New() any {
	return NewPayOrderReq()
}

func (x *PayOrderReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *PayOrderReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (p *PayOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *p)
}

type PayOrderResp struct {
	Errno  ErrCode `json:"errno"`
	Errmsg string  `json:"errmsg"`
	Data   *Order  `json:"data"`
}

func NewPayOrderResp() *PayOrderResp {
	return &PayOrderResp{}
}

func (x *PayOrderResp) New() any {
	return NewPayOrderResp()
}

func (x *PayOrderResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *PayOrderResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

func (x *PayOrderResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *PayOrderResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *PayOrderResp) GetData() (r *Order) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *PayOrderResp) SetData(v *Order) {
	if x != nil {
		x.Data = v
	}
}

func (p *PayOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderResp(%+v)", *p)
}

type ShipOrderReq struct {
	Id string `json:"id"`
}

func NewShipOrderReq() *ShipOrderReq {
	return &ShipOrderReq{}
}

func (x *ShipOrderReq) New() any {
	return NewShipOrderReq()
}

func (x *ShipOrderReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *ShipOrderReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (p *ShipOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShipOrderReq(%+v)", *p)
}

type ShipOrderResp struct {
	Errno  ErrCode `json:"errno"`
	Errmsg string  `json:"errmsg"`
	Data   *Order  `json:"data"`
}

func NewShipOrderResp() *ShipOrderResp {
	return &ShipOrderResp{}
}

func (x *ShipOrderResp) New() any {
	return NewShipOrderResp()
}

func (x *ShipOrderResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *ShipOrderResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

func (x *ShipOrderResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *ShipOrderResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *ShipOrderResp) GetData() (r *Order) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *ShipOrderResp) SetData(v *Order) {
	if x != nil {
		x.Data = v
	}
}

func (p *ShipOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShipOrderResp(%+v)", *p)
}
