// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"fmt"
)

type PingReq struct {
	Name string `json:"name"`
}

func NewPingReq() *PingReq {
	return &PingReq{}
}

func (x *PingReq) New() any {
	return NewPingReq()
}

func (x *PingReq) GetName() (r string) {
	if x != nil {
		return x.Name
	}
	return r
}

func (x *PingReq) SetName(v string) {
	if x != nil {
		x.Name = v
	}
}

func (p *PingReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingReq(%+v)", *p)
}

type PingResp struct {
	Errno  ErrCode `json:"errno"`
	Errmsg string  `json:"errmsg"`
	Data   string  `json:"data"`
}

func NewPingResp() *PingResp {
	return &PingResp{}
}

func (x *PingResp) New() any {
	return NewPingResp()
}

func (x *PingResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *PingResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

func (x *PingResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *PingResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *PingResp) GetData() (r string) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *PingResp) SetData(v string) {
	if x != nil {
		x.Data = v
	}
}

func (p *PingResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingResp(%+v)", *p)
}
