// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"fmt"
)

type UserLevel int32

const (
	UserLevel_Normal UserLevel = 0
	UserLevel_VIP    UserLevel = 1
)

var (
	UserLevel_name = map[int32]string{
		0: "Normal",
		1: "VIP",
	}
	UserLevel_value = map[string]int32{
		"Normal": 0,
		"VIP":    1,
	}
)

func OneOfUserLevel(i int32) bool {
	_, ok := UserLevel_name[i]
	return ok
}

type User struct {
	Id    string    `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
	Level UserLevel `json:"level"`
}

func NewUser() *User {
	return &User{}
}

func (x *User) New() any {
	return NewUser()
}

func (x *User) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *User) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *User) GetName() (r string) {
	if x != nil {
		return x.Name
	}
	return r
}

func (x *User) SetName(v string) {
	if x != nil {
		x.Name = v
	}
}

func (x *User) GetEmail() (r string) {
	if x != nil {
		return x.Email
	}
	return r
}

func (x *User) SetEmail(v string) {
	if x != nil {
		x.Email = v
	}
}

func (x *User) GetLevel() (r UserLevel) {
	if x != nil {
		return x.Level
	}
	return r
}

func (x *User) SetLevel(v UserLevel) {
	if x != nil {
		x.Level = v
	}
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

type RegisterUserReq struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func NewRegisterUserReq() *RegisterUserReq {
	return &RegisterUserReq{}
}

func (x *RegisterUserReq) New() any {
	return NewRegisterUserReq()
}

func (x *RegisterUserReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *RegisterUserReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *RegisterUserReq) GetName() (r string) {
	if x != nil {
		return x.Name
	}
	return r
}

func (x *RegisterUserReq) SetName(v string) {
	if x != nil {
		x.Name = v
	}
}

func (x *RegisterUserReq) GetEmail() (r string) {
	if x != nil {
		return x.Email
	}
	return r
}

func (x *RegisterUserReq) SetEmail(v string) {
	if x != nil {
		x.Email = v
	}
}

func (p *RegisterUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterUserReq(%+v)", *p)
}

type RegisterUserResp struct {
	Errno  ErrCode `json:"errno"`
	Errmsg string  `json:"errmsg"`
	Data   *User   `json:"data"`
}

func NewRegisterUserResp() *RegisterUserResp {
	return &RegisterUserResp{}
}

func (x *RegisterUserResp) New() any {
	return NewRegisterUserResp()
}

func (x *RegisterUserResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *RegisterUserResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

func (x *RegisterUserResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *RegisterUserResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *RegisterUserResp) GetData() (r *User) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *RegisterUserResp) SetData(v *User) {
	if x != nil {
		x.Data = v
	}
}

func (p *RegisterUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterUserResp(%+v)", *p)
}

type UpgradeUserReq struct {
	Id string `json:"id"`
}

func NewUpgradeUserReq() *UpgradeUserReq {
	return &UpgradeUserReq{}
}

func (x *UpgradeUserReq) New() any {
	return NewUpgradeUserReq()
}

func (x *UpgradeUserReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

func (x *UpgradeUserReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (p *UpgradeUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpgradeUserReq(%+v)", *p)
}

type UpgradeUserResp struct {
	Errno  ErrCode `json:"errno"`
	Errmsg string  `json:"errmsg"`
	Data   *User   `json:"data"`
}

func NewUpgradeUserResp() *UpgradeUserResp {
	return &UpgradeUserResp{}
}

func (x *UpgradeUserResp) New() any {
	return NewUpgradeUserResp()
}

func (x *UpgradeUserResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *UpgradeUserResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

func (x *UpgradeUserResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *UpgradeUserResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *UpgradeUserResp) GetData() (r *User) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *UpgradeUserResp) SetData(v *User) {
	if x != nil {
		x.Data = v
	}
}

func (p *UpgradeUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpgradeUserResp(%+v)", *p)
}
