spring.go-redis.main.addr=127.0.0.1:6379
spring.redigo.main.addr=127.0.0.1:6379
spring.gorm.main.url=root:123456@(127.0.0.1:3306)/test?timeout=500ms&readTimeout=500ms&writeTimeout=500ms&charset=utf8&parseTime=true&loc=Local